name: Docker Build and Sliplane Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/yeokiju/n8n:latest
            ghcr.io/yeokiju/n8n:${{ github.sha }}

      - name: Deploy to Sliplane
        run: |
          curl "https://api.sliplane.io/deploy/service_c9gwfpq7ilgm/${{ secrets.DEPLOY_SECRET }}?tag=${{ github.sha }}"
